### ISSUE TITLE
Game crashes when you place sand next to redstone seive

### ISSUE THREAD

**Issue by NoobiusMcGuffin** [Globox1997/EarlyStage#1]
Title self explanatory
Also, how are you supposed to get wood? Like, you need a crafting table for the axe, but you can't make a crafting table without wood, and you can't break wood without an axe... which you can't get without a crafting table.  Maybe to fix this you add a sticks to planks recipe so that we can make the crafting table.

**Comment by Globox1997** [comment]
Please post the crash log here as a file
you have to break leaves to get sticks

**Comment by Cooliosity** [comment]
NoobiusMcGuffin hat gefragt wie er überhaupt eine Axt bekommen soll, wenn das Rezept für die Axt eine Werkbank benötigt und vorgeschlagen, dass du ein Rezept hinzufügst, das erlaubt Stöcke zu Brettern umzucraften. Meiner Meinung nach müsste man dann aber für ein angemessenes Rezept ziemlich viele Stöcke abbauen, weshalb ich vorschlage, dass du einfach das Rezept für die Axt um einen Stock reduzierst, sodass keine Werkbank mehr benötigt wird.

**Comment by Globox1997** [comment]
Pls remain in english language :)
The main issue is here only what the title says cause to get an axe is not hard.
leaves drop sticks with this mod and with the latest update, flints lay on the ground or find yourself some gravel :)
The idea to change the recipe of the flint axe is not bad but imo it doesn't really fit to mc and this mod

**Comment by Globox1997** [comment]
This is basically fixed with the crafting rock :)
