### ISSUE TITLE
The Crafting Rock isn't marked as pickaxe breakable

### ISSUE THREAD

**Issue by lumiscosity** [Globox1997/EarlyStage#10]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.24

### Mod Version

1.0.11

### Describe the Issue

The Crafting Rock isn't broken faster when using a pickaxe, and never drops.

### latest.log

Logs aren't relevant for this issue.

### Do you use any other mods except the required ones?

<details>

<summary>Full modlist</summary> 
        - alternate-current 1.7.0
	- architectury 9.1.12
	- armorful 2.0.2+1.20
	   \-- static-content 1.0.1-1.16.2
	        \-- staticdata 1.1.2
	- athena 3.1.1
	- audaki_cart_engine 2.0.6
	- authme 7.0.2+1.20
	- balm-fabric 7.1.4
	- bedrockify 1.9.1+mc1.20
	   \-- panorama_screens 1.0+fabric+mc1.20
	- betteradvancements 0.3.2.161
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.3
	- betterendisland 1.20-Fabric-2.0.4
	- betterfortresses 1.20-Fabric-2.0.5
	- betterjungletemples 1.20-Fabric-2.0.4
	- bettermineshafts 1.20-Fabric-4.0.4
	- betteroceanmonuments 1.20-Fabric-3.0.3
	- betterstrongholds 1.20-Fabric-4.0.3
	- betterwitchhuts 1.20-Fabric-3.0.3
	- biomemakeover 1.20.1-1.11.4
	   \-- taniwha 1.20.0-5.4.4
	- bookshelf 20.1.6
	- breakfast 1.0.0
	- c2me 0.2.0+alpha.11.0
	   |-- c2me-base 0.2.0+alpha.11.0
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.0
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.0
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.0
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.0
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.0
	   |-- c2me-notickvd 0.2.0+alpha.11.0
	   |-- c2me-opts-allocs 0.2.0+alpha.11.0
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.0
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.0
	   |-- c2me-opts-math 0.2.0+alpha.11.0
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.0
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.0
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.0
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.0
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.0
	   |-- c2me-server-utils 0.2.0+alpha.11.0
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.0
	   |-- c2me-threading-lighting 0.2.0+alpha.11.0
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.0
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- chalk 2.2.0
	   \-- simplefabric 1.0.0
	- chatabove 1.0
	- chatcalc 3.0.15
	- chickensshed 1.5.0+1.20.1
	- cinderscapes 4.0.8
	   |-- biolith 1.0.0-alpha.8
	   |    \-- terraform-surfaces-api-v1 7.0.1
	   |-- cinderscapes-client 4.0.8
	   |-- cinderscapes-common 4.0.8
	   |-- cinderscapes-worldgen 4.0.8
	   |-- terraform-biome-remapper-api-v1 7.0.1
	   |-- terraform-shapes-api-v1 7.0.1
	   |-- terraform-surfaces-api-v1 7.0.1
	   \-- terraform-wood-api-v1 7.0.1
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- collective 6.72
	- comforts 6.3.4+1.20.1
	   \-- spectrelib 0.13.14+1.20.1
	- companion 5.1.0
	- controlling 12.0.2
	- copperhopper 0.5.1+1.20.1
	- crafttweaker 14.0.17
	- crawl 0.12.0
	   \-- mm 2.3
	- crunchy-crunchy-advancements 1.5.2+1.19.3
	   \-- folk_sisby_kaleido-config 0.1.0+1.1.0-beta.3
	- dashloader 5.0.0-beta.2+1.20.0
	   |-- com_github_luben_zstd-jni 1.5.2-2
	   |-- dev_notalpha_taski 2.1.0
	   \-- dev_quantumfusion_hyphen 0.4.0-rc.3
	- dawn 5.0.0
	   |-- terraform-shapes-api-v1 7.0.1
	   \-- terraform-wood-api-v1 7.0.1
	- earlystage 1.0.11
	- ears 1.4.6
	- elytratrims 1.4.1
	   |-- com_github_llamalad7_mixinextras 0.2.0
	   \-- conditional-mixin 0.3.2
	- emi 1.0.23+1.20.1+fabric
	- emi_loot 0.6.5+1.20.1
	- emitrades 1.2.0+mc1.20.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- enchdesc 17.0.8
	- endorium 1.0.4
	- endrem 5.2.2
	- enhancedblockentities 0.9+1.20
	   |-- advanced_runtime_resource_pack 0.6.7
	   \-- spruceui 5.0.0+1.20
	- enhancermod 1.4.1.1-1.20.1
	- everycomp 1.20-2.6.15
	- fabric-api 0.90.4+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.2+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.6+d7b148e077
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.1+195226a777
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.11+kotlin.1.9.20
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.20
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.20
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
	- fabrication 3.4.0+1.20
	   \-- lib39-deferral 1.5.0-pre2.2+1.19.3
	- fabricloader 0.14.24
	- fallingleaves 1.15.4
	- fancymenu 2.14.10
	- faster_entity_animations 1.6
	- faux-custom-entity-data 6.0.1
	- ferritecore 6.0.1
	- geckolib 4.2.4
	   \-- com_eliotlash_mclib_mclib 20
	- geophilic v2.0.0-mc1.20u1.20.1
	- glass_armor 1.0.0+1.20.x
	- great_big_world 1.2.6
	   \-- creo 1.0.0-beta.17
	- hauntfurnace 0.2-1.20.1
	   \-- team_reborn_energy 3.0.0
	- here-be-no-dragons 1.0.0
	- highlight 2.0.1
	- igneous-machines 1.2.0+1.20
	- immediatelyfast 1.2.6+1.20.2
	   \-- net_lenni0451_reflect 1.2.4
	- incendium 5.3.3
	- indium 1.0.27+mc1.20.1
	- inmis 2.7.2-1.20.1
	   \-- omega-config 1.2.3-1.18.1
	- inventoryessentials 8.2.1
	- invisibleframes 1.1.0
	- jade 11.6.2
	- java 17
	- jineric b6.0.1+1.20
	   \-- mm 2.3
	- konkrete 1.7.0
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- kubejs 2001.6.3-build.83
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- librarians_balance_mr 1.2
	- lithium 0.11.2
	- map_shirts 0.6.0
	- maptooltip 3.0.0
	- memoryleakfix 1.1.2
	- mes 1.3-1.20-fabric
	- minecraft 1.20.1
	- mod-loading-screen 1.0.4
	   \-- com_formdev_flatlaf 3.0
	- modmenu 7.2.2
	- moonlight 1.20-2.8.53
	- morechathistory 1.1.1
	- mortar 1.0.2
	- mossierdeepslate 2.0.2
	- naturescompass 1.20.1-2.2.3-fabric
	- netheritehorsearmor 0.4.6-1.20.1
	- nicertabbackground 2.0.0
	- njb 1.1.0
	- norecipebook 2.4+1.20.1
	- nullscape 1.2.3
	- openloader 19.0.3
	- owo 0.11.2+1.20
	   \-- blue_endless_jankson 1.2.2
	- patched 3.2.3+1.20.1
	- pearfection 1.1.1
	- promenade 4.1.1
	   \-- biolith 1.0.0-alpha.8
	        \-- terraform-surfaces-api-v1 7.0.1
	- pufferblocks 1.0.0
	- reeses-sodium-options 1.6.5+mc1.20.1-build.95
	- resourcefullib 2.1.13
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- rhino 2001.2.2-build.11
	- scarecrowsterritory 1.1.11
	- searchables 1.0.2
	- securecrops 1.0.4+1.20
	- shulkerboxtooltip 4.0.4+1.20.1
	- shulkerdropstwo 3.1
	- simple_copper_pipes 1.14
	- slash-portal 1.0.0
	- smwyg 1.1.1
	- snifferplus 0.2.0
	- snuffles 1.0.0+1.20
	- sodium 0.5.3
	- sodium-extra 0.5.1+mc1.20.1-build.112
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- starlight 1.1.2+fabric.dbc156f
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.15
	- supplementaries 1.20-2.6.19
	   \-- mixinsquared 0.1.1
	- swingthrough 1.0.4+1.19
	- symbol-chat 1.20.1-1.1.2
	- tectonic 2.1.1
	- terrablender 3.0.0.169
	- tipsmod 12.0.3
	- tooltipfix 1.1.1-1.20
	- transmog 1.2.4+1.20
	- traverse 7.0.9
	   |-- biolith 1.0.0-alpha.8
	   |    \-- terraform-surfaces-api-v1 7.0.1
	   |-- terraform-biome-remapper-api-v1 7.0.1
	   |-- terraform-config-api-v1 7.0.1
	   |-- terraform-surfaces-api-v1 7.0.1
	   |-- terraform-tree-api-v1 7.0.1
	   |-- terraform-wood-api-v1 7.0.1
	   |-- traverse-client 7.0.9
	   |-- traverse-common 7.0.9
	   \-- traverse-worldgen 7.0.9
	- trowel 1.2.1@1.20
	- twigs 3.1.0
	- visuality 0.7.1+1.20
	- wilderwild 2.1.11-Fabric+1.20.1
	   \-- frozenlib 1.3.15-Fabric+1.20.1
	- xaeroarrowfix 1.3+1.20
	- xaerominimap 23.8.4
	- xaeroworldmap 1.36.0
	- yet_another_config_lib_v3 3.2.1+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   \-- org_quiltmc_parsers_gson 0.2.1
	- yungsapi 1.20-Fabric-4.0.2
	   \-- org_javassist_javassist 3.29.2-GA
	- zoomify 2.11.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
</details>

**Comment by Globox1997** [comment]
Should be fixed with this [https://github.com/Globox1997/EarlyStage/commit/56eee0a46123313cd3097a435862298b30c23aaa](https://github.com/Globox1997/EarlyStage/commit/56eee0a46123313cd3097a435862298b30c23aaa)
