### ISSUE TITLE
Planning on adding the ability to create custom recipes with crafting rock via datapack?

### ISSUE THREAD

**Issue by FluffyTG** [Globox1997/EarlyStage#16]
### Make sure you are not opening a duplicate.

- [x] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

I am making a modpack, and I want to restrict the player for a bit longer than the initial flint tools and was wondering if the ability to add custom crafting rock recipes is in the works, possibly even being able to configure the number of rock hits needed.

**Comment by Globox1997** [comment]
I don't have plans to but the crafting rock ingredients are bound to the usable_crafting_rock_items tag.
With this item tag you should be able to do it.

**Comment by FluffyTG** [comment]
Oh cool, then yeah that makes it very easy to tweak it, cool, thanks!!
