### ISSUE TITLE
Replace wood tools with flint tools

### ISSUE THREAD

**Issue by Tar1q22** [Globox1997/EarlyStage#22]
### Make sure you are not opening a duplicate.

- [X] I have searched the issue tracker and did not find an issue describing my bug/feature.

### Description of your suggestion.

It would be cool if there was and option to have flint tools completely replace wood tools, having the same stats as wood tools. Just a nice touch that would make thing make a bit more sense as well as making flint tools a bit more useful.

**Comment by Globox1997** [comment]
Mh you would need to disable those with a mod like cubejs.
not a bad idea but not in my vision.
