### ISSUE TITLE
Crafting rock can't be used

### ISSUE THREAD

**Issue by Flamaghl** [Globox1997/EarlyStage#5]
Hello,

I create this issue as a follow up of "Progression is impossible #4"

Currently, when you break leaves and flints you get flint and sticks correctly which is Ok.
You can also break rocks to craft your crafting rock, which is also OK.

The issue then, is that I can't seem to use the crafting rock correctly... So here are the different tests I performed :
1- I can visually see the sticks and flints put on it, but even with the correct tool shape nothing happens
2 - Wether I right click on the crafting rock or left click it, nothing happens
3 - When I break it by hand, the items displayed drop correctly
4 - Does the crafting rock have a direction ? I mean when you put items in it, they are sometimes put backward or sideways as if the direction is locked
5 - Is the crafting rock mirrored ? I mean when you put items in the grid, they are put in the slot opposite of the one you right clicked
6 - I Can correctly craft flint items in vanilla crafting table (but then, without cheating it is impossible to get wood)
 
I Said at the beginning that it was a follow up of "Progression is impossible #4", since this actually blocks the progression...
You can break sticks, stones and flints, but as you cannot craft flint tools using the crafting rock, you cannot harvest wood to craft the vanilla crafting table and are blocked

![IMG_20230131_150319__01](https://user-images.githubusercontent.com/120495926/215782673-47b1f7c0-d4b8-496f-9744-3afdad1b5129.jpg)
![IMG_20230131_150343__01__01](https://user-images.githubusercontent.com/120495926/215782677-fd49c33b-403d-4e12-a77e-abc543908c42.jpg)

**Comment by Flamaghl** [comment]
FYI,
I'm using earlystage-1.0.5.jar from curseforge, on fabric 0.14.3 for MC 1.19.2 :)

**Comment by Globox1997** [comment]
Thanks for reporting, added a tooltip to the crafting rock which explains a little more the crafting process with [https://github.com/Globox1997/EarlyStage/commit/857db31d0bf3cdf4ef5b79e86ad03680a794932a](https://github.com/Globox1997/EarlyStage/commit/857db31d0bf3cdf4ef5b79e86ad03680a794932a).
You have to hit the crafting rock with a rock a couple of times to craft items.
Have to fix the mirroring issue still...

**Comment by Flamaghl** [comment]
Oh, thank you ! 
I understood I didn't know how to use it when I saw other post saying the mod is cool and all haha 😅 Thank you very much for your answer ! Didn't try to hit it with a rock at all... But other than that I love the concept of this mod 😄

**Comment by Flamaghl** [comment]
Do I close the issue thanks to your new tooltip, or do I keep it open for the item mirror/locked direction thingy ?

**Comment by Globox1997** [comment]
This can now be closed, added correct rotation :)
