### ISSUE TITLE
How this work? Flint tools still require 3x3 grid.

### ISSUE THREAD

**Issue by Chris-Creates** [Globox1997/EarlyStage#7]
I really like the idea here, but I tried the mod and the flint tools still require a 3x3 grid, which means you need a crafting table, which means you need planks, which means you need logs, which you can't get because you can't punch trees, you need an axe first.

I'm confused. How am I supposed to get that first flint axe if it still requires a crafting table which requires me to already have an axe?

I can't make anything with this mod lol.

**Comment by Globox1997** [comment]
:D you need the crafting rock

**Comment by Chris-Creates** [comment]
> :D you need the crafting rock

Ahh. SHoulld probably mention that somewhere lol.

It looks like the rocks and flint dont spawn in all biomes? Or at least not ones added by other mods?

**Comment by Simiea** [comment]
Just find them. I seem to always find them no matter where i am. The flint might be annoying to find in some biomes but rocks are easy to find

**Comment by TheSexyYeti** [comment]
How do you even use the crafting rock?.  All the tooltip says is to hit the crafting rock with a rock a few times to craft. But no gui pops up, and there's doesn't seem to be any interaction or anything to place crafting materials into the crafting grid of the crafting rock.  The crafting rock doesn't even seem to show up in JEI indicating it's a viable crafting workbench. Either it's bugged, or you left something out on how to use it.

**Comment by Globox1997** [comment]
So the final explanation:
- Gather sticks from leaves
- Gather flint and rock from the ground
- Craft a crafting rock (inventory crafting used)
- Place the crafting rock on the ground and put sticks and flint on it
- hit the crafting rock with a rock (right click) to craft the flint tool
