### ISSUE TITLE
Crafting stone Not working

### ISSUE THREAD

**Issue by TheSexyYeti** [Globox1997/EarlyStage#8]
### Minecraft Version

1.19.x

### Mod Loader Version

Fabric 0.14.22

### Mod Version

1.0.10

### Describe the Issue

The crafting stone has no functionality. How do I craft tools or anything if you can't put anything into the crafting stone or click it to open up a Gui to craft anything. It literally brings all gameplay to a halt. JEI doesn't even show the crafting stone as a viable crafting station for recipes.

### latest.log

A log of what?. It didn't cause a crash. So what log do you expect me to put here?.

**Comment by Globox1997** [comment]
you have to put items on it, like sticks and flint. After that you hit it with another rock (right click) to craft the item.
