### ISSUE TITLE
1.20.1 update?

### ISSUE THREAD

**Issue by macaroni0423** [Globox1997/EarlyStage#9]
### Make sure you are not opening a duplicate.

- [ ] I have searched the issue tracker and did not find an issue describing my bug.

### Description of your suggestion.

I think your mod is cool. However, there is no 1.20.1 version of this mod, so I have difficulty making a modpack.
Can you update this mod?

**Comment by Globox1997** [comment]
Waiting for fabric shield lib update

**Comment by Globox1997** [comment]
Updated without fabricshieldlib and disabled wooden shield.
